applications:
  - name: frontend
    image:
      repository: frontend
      tag: v0.1.0
      containerPort: 80
    deployment:
      replicas: 1
    service:
      port: 80
    ingress:
      - host: <hostname>
        path: /
        pathType:
    env:
      - SOME
      - EXAMPLE
      - ENVS
    secret:
      - EXAMPLE_SECRET

  - name: backend
    image:
      repository: backend
      tag: v0.1.0
      containerPort: 4000
    deployment:
      replicas: 1
    service:
      port: 80
    ingress:
      - host: <hostname>
        path: /backend
        pathType:
    env:
      - SOME
      - MORE
      - EXAMPLE
      - ENVS
    secret:
      - ANOTHER_EXAMPLE_SECRET
